# -*- coding: utf-8 -*-
"""ProblemSolvingDLNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RR4NKmUrDINMJ55qz5UQ2uPcgARrmYDo
"""

from google.colab import files
files.upload()  # Upload kaggle.json here

!pip install kaggle

# Move kaggle.json to proper folder
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Example: Tomato Leaf Disease YOLOv8 dataset
!kaggle datasets download -d vasantharank/tomato-leaf-disease-detection-yolov8-dataset

# Unzip the dataset
!unzip tomato-leaf-disease-detection-yolov8-dataset.zip -d /content/tomato_leaf_disease_dataset

# Create YAML in Colab
yaml_content = """
train: /content/tomato_leaf_disease_dataset/train/images
val: /content/tomato_leaf_disease_dataset/val/images

nc: 10
names: ['Tomato_mosaic_virus', 'Target_Spot', 'Bacterial_spot', 'Early_blight', 'Late_blight', 'Leaf_Mold', 'Septoria_leaf_spot', 'Spider_mites', 'Two_spotted_spider_mite', 'Healthy']
"""

with open('/content/tomato_leaf_disease.yaml', 'w') as f:
    f.write(yaml_content)

!pip install ultralytics

from ultralytics import YOLO

# Load pretrained YOLOv8n
model = YOLO('yolov8n.pt')

import os
import shutil
import random

# Paths
train_images = '/content/tomato_leaf_disease_dataset/train/images'
train_labels = '/content/tomato_leaf_disease_dataset/train/labels'
val_images = '/content/tomato_leaf_disease_dataset/val/images'
val_labels = '/content/tomato_leaf_disease_dataset/val/labels'

# Create val folders
os.makedirs(val_images, exist_ok=True)
os.makedirs(val_labels, exist_ok=True)

# List all images
all_images = [f for f in os.listdir(train_images) if f.endswith('.jpg') or f.endswith('.png')]

# Take 10% of images for validation
val_count = int(0.1 * len(all_images))
val_samples = random.sample(all_images, val_count)

# Move selected images and corresponding labels to val folder
for img in val_samples:
    # Move image
    shutil.move(os.path.join(train_images, img), os.path.join(val_images, img))

    # Move label
    label_file = os.path.splitext(img)[0] + '.txt'
    shutil.move(os.path.join(train_labels, label_file), os.path.join(val_labels, label_file))

print(f"Moved {val_count} images to validation folder")

train: '/content/tomato_leaf_disease_dataset/train/images'
val: '/content/tomato_leaf_disease_dataset/val/images'

from ultralytics import YOLO

model = YOLO('yolov8n.pt')

model.train(
    data='/content/tomato_leaf_disease.yaml',
    epochs=10,
    imgsz=640,
    batch=16
)

metrics = model.val()
print(metrics)

results = model.predict(
    source='/content/tomato_leaf_disease_dataset/val/images',
    conf=0.5,
    save=True
)
results[0].show()  # Shows first predicted image

plt.figure(figsize=(10,6))
plt.plot(df['epoch'], df['precision'], label='Precision')
plt.plot(df['epoch'], df['recall'], label='Recall')
plt.plot(df['epoch'], df['mAP_0.5'], label='mAP50')
plt.xlabel('Epochs')
plt.ylabel('Metric')
plt.title('YOLOv8 Validation Metrics')
plt.legend()
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load YOLOv8 training results
results_csv = '/content/runs/detect/train2/results.csv'  # adjust folder if needed
df = pd.read_csv(results_csv)

# Plot Box, Class, and DFL loss
plt.figure(figsize=(10,6))
plt.plot(df['epoch'], df['train/box_loss'], label='Box Loss')
plt.plot(df['epoch'], df['train/cls_loss'], label='Class Loss')
plt.plot(df['epoch'], df['train/dfl_loss'], label='DFL Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('YOLOv8 Training Loss Curves')
plt.legend()
plt.grid(True)
plt.show()

import cv2
from matplotlib import pyplot as plt

# Path to predicted images
pred_folder = '/content/runs/detect/predict/'

# Show first 3 predictions
pred_images = [f for f in os.listdir(pred_folder) if f.endswith('.jpg')][:3]

for img_name in pred_images:
    img_path = pred_folder + img_name
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    plt.figure(figsize=(8,6))
    plt.imshow(img)
    plt.axis('off')
    plt.title(f'Prediction: {img_name}')
    plt.show()

# Run validation
metrics = model.val()

# Get mean results
precision, recall, mAP50, mAP5095 = metrics.mean_results()

# Print neatly
print("====== Validation Metrics ======")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"mAP@0.5: {mAP50:.2f}")
print(f"mAP@0.5:0.95: {mAP5095:.2f}")